spring:
  application:
    name: easy-spring-auth
server:
  port: 8083
#  view-component:
#    local-development: true
#org:
#  eclipse:
#    store:
#      root: de.tschuehly.easy.spring.auth.store.Root
#      storage-directory: ./storage
gg:
  jte:
    developmentMode: true